application/dbusproxy/dldbushandler.cpp, application/dbusproxy/dldbushandler.h, application/dbusproxy/dldbusinterface.h, application/logauththread.cpp, logViewerService/assets/data/com.deepin.logviewer.xml, logViewerService/logviewerservice.cpp, logViewerService/logviewerservice.h, tests/src/ut_logauththread.cpp
原因是输入的内核日志文件达到接近40MB，超过了dbus的承载上限
修改方法是添加流式传输接口传输数据，防止dbus崩溃
Log: 修复内核日志体量过大时导致的dbus崩溃
Bug: https://pms.uniontech.com/bug-view-149507.html
=> fix: 修复内核日志体量过大时导致的dbus崩溃

application/CMakeLists.txt
Log: Use as-needed to enhance compatibility with linker
Signed-off-by: Han Gao <rabenda.cn@gmail.com>
=> fix: use as-needed instead of as-need

logViewerService/logviewerservice.cpp
原因是未校验输出目录的路径，导致在特殊情况下可以进行shell注入
解决方法是添加输出目录的路径校验，必须路径存在才能执行后续操作
Log: 修复导出日志可能带来的shell注入问题
=> fix: 修复导出日志可能带来的shell注入问题

application/logauththread.cpp, application/logfileparser.cpp, logViewerService/logviewerservice.cpp
154893 【摸底】【日志收集工具】【E500-50258】刷新频率设置为10s后，切换到内核日志时应用卡死
原因分析：该函数会查找到所有内核日志文件，并返回文件名列表，同时会对所有文件解压缩，内核历史日志文件都挺大的，一次性全部解压缩就会很耗时。
解决办法：在查找所有内核日志文件名列表时，不解压缩文件，在内核日志解析线程中，解压一个处理一个，同时配合以前的解析500条记录就返回给界面展示的逻辑，可以解决该问题。
Log: 修复bug154893
Bug: https://pms.uniontech.com/bug-view-154893.html
=> fix: 修复bug154893

logViewerService/logviewerservice.cpp
在dbus调起时校验调用者以防止非法调用
Log: 在dbus调起时校验调用者以防止非法调用
=> fix: 在dbus调起时校验调用者以防止非法调用

logViewerService/logviewerservice.cpp
Replace /usr/bin/deepin-log-viewer in logViewerService/logviewerservice.cpp with just deepin-log-viewer
Related: linuxdeepin/developer-center#3374
The commit message should be fixed now, please review the PR and merge if there are no outstanding issues, thanks :smile:
=> fix: avoid hardcoded exec path

debian/control, debian/deepin-log-viewer.install
Description: 提交deepin-log-viewer.install文件
Log: 修复更新版本至5.9.14-1后，启动器和桌面的日志收集工具消失
Bug: https://pms.uniontech.com/bug-view-182619.html
=> fix: 修复更新版本至5.9.14-1后，启动器和桌面的日志收集工具消失

application/displaycontent.cpp
Description: 切换导航栏后，需要重新设置最小高度
Log: 修复其他日志中，日志区域最小高度过大
Bug: https://pms.uniontech.com/bug-view-182953.html
=> fix: 修复其他日志中，日志区域最小高度过大

application/displaycontent.cpp
Description: 切换导航栏时，重新计算其他日志列表默认高度
Log: 修复其他日志中，日志列表与区域默认高度错误
Bug: https://pms.uniontech.com/bug-view-182955.html
=> fix: 修复其他日志中，日志列表与区域默认高度错误

application/logapplicationhelper.cpp
Description: 添加缺少配置
Log: 修复/var/log/fontconfig.log 其他日志列表中缺少配置
Bug: https://pms.uniontech.com/bug-view-182915.html
=> fix: 修复/var/log/fontconfig.log 其他日志列表中缺少配置

application/logapplicationhelper.cpp
Description: "~"符号扩展为用户主目录是shell执行的替换，需要用代码实现该功能
Log: 添加配置路径支持“～”符号
Bug: https://pms.uniontech.com/bug-view-183009.html
=> feat: 添加配置路径支持“～”符号

application/logapplicationhelper.cpp, application/utils.cpp, application/utils.h
Description: 添加过滤非text格式文件功能
Log: 修复自定义日志配置，配置非text格式未忽略该文件
Bug: https://pms.uniontech.com/bug-view-183011.html
=> fix: 修复自定义日志配置，配置非text格式未忽略该文件

application/logoocfileparsethread.cpp
Description: pkexec鉴权，如果路径传入为空，则一直阻塞没有返回值；增加路径为空判断
Log: 修复gsetting配置自定义配置日志路径为空字符串，日志信息界面一直转圈
Bug: https://pms.uniontech.com/bug-view-183371.html
=> fix: 修复gsetting配置自定义配置日志路径为空字符串，日志信息界面一直转圈

application/displaycontent.cpp
Description: 列表控件隐藏，失去焦点，焦点自动调整到导出按钮上；状态切换，不用一开始就直接隐藏列表控件，有需要再隐藏
Log: 修复其他日志中，选中任意日志文件，“导出”按钮不应该聚焦状态
Bug: https://pms.uniontech.com/bug-view-182989.html
=> fix: 修复其他日志中，选中任意日志文件，“导出”按钮不应该聚焦状态

application/displaycontent.cpp, application/logoocfileparsethread.cpp
Description: m_curTreeIndex标记没有重置，有几率会出现新旧标记相等而不刷新日志内容的情况
Log: 修复自定义日志配置无后缀名的文本文件，无法获取文本
Bug: https://pms.uniontech.com/bug-view-183671.html
=> fix: 修复自定义日志配置无后缀名的文本文件，无法获取文本

application/logallexportthread.cpp
原因是在导出全部日志的时候没有将其它日志和自定义日志的路径加入导出列表中
解决方法是添加相关代码
Log: 修复导出所有日志未包含其它日志和自定义日志
=> fix: 修复导出所有日志未包含其它日志和自定义日志

application/logapplicationhelper.cpp, application/utils.cpp
原因是在过滤非文本文件的时候，将mime type为x-zerosize的空白无后缀文件也过滤掉了
解决方法是添加过滤白名单，同时进一步过滤掉不存在的文件
Log: 修复自定义日志无法监控空白无后缀文件
Bug: https://pms.uniontech.com/bug-view-183671.html
=> fix: 修复自定义日志无法监控空白无后缀文件

application/CMakeLists.txt, debian/deepin-log-viewer.install
原因是之前添加了install文件控制安装的内容，但没有添加安装帮助手册
解决方法是将帮助手册文件添加上去
Log: 修复未安装帮助手册文件
Bug: https://pms.uniontech.com/bug-view-187497.html
=> fix: 修复未安装帮助手册文件

application/displaycontent.cpp
原因是在传入搜索函数的字符串为空时，函数直接返回了
解决方法是删除直接返回的代码
Log: 修复搜索框从有字到无字时不做刷新
Bug: https://pms.uniontech.com/bug-view-187403.html
=> fix: 修复搜索框从有字到无字时不做刷新

application/displaycontent.cpp
原因是新需求开发导致控件层级出错,新控件遮挡了用于显示文案的标签
解决方法是在显示文案的时候主动将标签置顶
Log: 修复无搜索结果时没有显示提示文案
Bug: https://pms.uniontech.com/bug-view-187395.html
=> fix: 修复无搜索结果时没有显示提示文案

logViewerService/logviewerservice.cpp
该内核日志为klv机器内核日志，大小为304.1MB，dbus服务将内容读取到QByteArray字节流数组中(3亿字节大小），其中包含2383处0x00非法字符字节。
为了保证QByteArray转QString不被0x00截断，原有方案是直接从字节流数组剔除0x00，但频繁改变3亿数组的大小，会带来极大时间损耗，导致读取日志卡住，达到dbus超时时限，内核日志视图展示为空白内容。参见https://pms.uniontech.com/bug-view-147301.html
因此本次修改方案为：将0x00替换为0x20(空格符)，以避免频繁改变数组大小带来的耗时开销。
Log: 修复获取内核日志读取卡住，展示空白的问题
Bug: https://pms.uniontech.com/bug-view-198137.html
=> fix: 修复获取内核日志读取卡住，展示空白的问题

application/dbusproxy/dldbushandler.cpp, application/logallexportthread.cpp, application/logapplicationhelper.cpp, application/logbackend.cpp, application/logcollectormain.cpp, application/utils.cpp
1.点击全部导出时，默认导出名称按当前时间更新
2.导出目录二级目录开关机事件目录名称变更为boot-shutdown-event
3.清除冗余日志
Log: 修复点击全部导出时，默认导出名称未按当前时间更新的问题
=> fix: 修复点击全部导出时，默认导出名称未按当前时间更新的问题

debian/changelog
1.修改审计筛选规则
2.添加崩溃日志功能
3.其他日志添加窗管日志
4.支持用cli命令全部导出日志
5.全部导出目录优化-日志种类按一二级目录划分
相关PR:
* linuxdeepin#161
* linuxdeepin#162
* linuxdeepin#166
* linuxdeepin#167
* linuxdeepin#168
* linuxdeepin#170
* linuxdeepin#174
Log: Update version to 6.1.0
=> chore: Update version to 6.1.0

application/logallexportthread.cpp, logViewerAuth/viewapplication.cpp
使用--no-pager参数获取全部崩溃日志，针对崩溃日志，使用finished信号获取命令行输出全部内容
Log: 修复崩溃日志显示不全的问题
Bug: https://pms.uniontech.com/bug-view-217023.html
=> fix: 修复崩溃日志显示不全的问题

application/logexportthread.cpp
仅有coredump文件才从标准输出读取压缩进度，其他时候不读取。
Log: 解决导出崩溃日志失败的问题
Bug: https://pms.uniontech.com/bug-view-217019.html
=> fix: 解决导出崩溃日志失败的问题

debian/changelog
1.修复崩溃日志显示不全的问题
2.修复崩溃日志导出失败的问题
3.添加accessible标签
相关PR：
* linuxdeepin#177
* linuxdeepin#180
* linuxdeepin#181
Log: Update version to 6.1.1
=> chore: Update version to 6.1.1

application/assets/deepin-logger, application/logallexportthread.cpp, application/logapplicationhelper.cpp, application/logbackend.cpp, application/logbackend.h, application/logexportthread.cpp, application/loglistview.cpp, application/logsettings.cpp, application/main.cpp, application/structdef.h, application/utils.cpp, application/utils.h, tests/src/ut_displaycontent.cpp, tests/src/ut_filtercontent.cpp, tests/ut_logviewerplugin/ut_logViewerPlugin.cpp
pkexec让程序以管理员身份运行，提权后的home路径保证能读取当前用户的home目录
Log: Fix the issue of missing 'apps' directory in command line export
Bug: https://pms.uniontech.com/bug-view-219629.html
=> fix: Fix the issue of missing 'apps' directory in command line export

application/main.cpp
Command line export initializes homePath first
Log: Command line export initializes homePath first
Bug: https://pms.uniontech.com/bug-view-219629.html
=> fix: Command line export initializes homePath first

application/DebugTimeManager.cpp, application/cliapplicationhelper.cpp, application/dbusmanager.cpp, application/dbusproxy/dldbushandler.cpp, application/displaycontent.cpp, application/journalappwork.cpp, application/journalbootwork.cpp, application/journalwork.cpp, application/logallexportthread.cpp, application/logapplicationhelper.cpp, application/logapplicationparsethread.cpp, application/logbackend.cpp, application/logexportthread.cpp, application/logfileparser.cpp, application/logoocfileparsethread.cpp, application/main.cpp, application/sharedmemorymanager.cpp, application/utils.cpp, logViewerAuth/viewapplication.cpp, logViewerService/logviewerservice.cpp, logViewerService/main.cpp
replace qDebug()、qInfo()、qWarning()、qCritical() width qCDebug()、qCInfo()、qCWarning()、qCCritical()
Log: add app log category
=> feat: add app log category

application/cliapplicationhelper.cpp, application/dbusproxy/dldbushandler.cpp, application/displaycontent.cpp, application/journalwork.cpp, application/logauththread.cpp, application/logbackend.cpp, application/logbackend.h, application/logfileparser.cpp, application/main.cpp, application/structdef.h, application/utils.cpp, application/utils.h, logViewerService/logviewerservice.cpp, translations/deepin-log-viewer.ts
Command line export by condition
Log: Command line export by condition
=> feat: Command line export by condition

application/logapplicationhelper.cpp, application/logapplicationhelper.h, application/logbackend.cpp, application/logbackend.h, application/main.cpp
fix export specify app log failed problem
Log: fix export specify app log failed problem
Bug: https://pms.uniontech.com/bug-view-225077.html
=> fix: fix export specify app log failed problem

application/dbusmanager.cpp, application/dbusmanager.h, application/displaycontent.cpp, application/logbackend.cpp, application/main.cpp
fix cli export kwin log failed problem
Log: fix cli export kwin log failed problem
Bug: https://pms.uniontech.com/bug-view-225427.html
=> fix: fix cli export kwin log failed problem

application/main.cpp
cli export -k can obtain parameters with spaces
Log: cli export -k can obtain parameters with spaces
Bug: https://pms.uniontech.com/bug-view-225795.html
=> fix: cli export -k can obtain parameters with spaces

application/logbackend.cpp
Solve the problem of audit failure with keywords when exporting in cli
Log: Solve the problem of audit failure with keywords when exporting in cli
=> fix: Solve the problem of audit failure with keywords when exporting in cli

application/main.cpp
cli export -t&-d option cannot use together, except for '-t app'
Log: cli export -t&-d option cannot use together
Bug: https://pms.uniontech.com/bug-view-226569.html
=> fix: cli export -t&-d option cannot use together

application/main.cpp
Improve cli export input prompts
Log: Improve cli export input prompts
Bug: pms.uniontech.com/bug-view-226623.html
=> chore: Improve cli export input prompts

application/logbackend.cpp
Fix the issue of exporting the boot log as empty by level in cli
Log: Fix the issue of exporting the boot log as empty by level in cli
Bug: https://pms.uniontech.com/bug-view-226673.html
=> fix: Fix the issue of exporting the boot log as empty by level in cli

application/configs/org.deepin.deepin-log-viewer.json, application/gschema/com.deepin.log-viewer.gschema.xml, application/logapplicationhelper.cpp, application/logapplicationhelper.h, application/logbackend.cpp, application/logsettings.cpp, application/logsettings.h
Coredump report time use is recorded by Dconfig/gsettings
Log: Coredump report time use is recorded by Dconfig/gsettings
Bug: https://pms.uniontech.com/bug-view-227219.html
=> fix: Coredump report time use is recorded by Dconfig/gsettings

application/logauththread.cpp, application/logauththread.h, application/logbackend.cpp, application/logfileparser.cpp, application/logfileparser.h
coredump map info only parsed in report coredump
Log: coredump map info only parsed in report coredump
Bug: https://pms.uniontech.com/bug-view-233653.html
=> fix: coredump map info only parsed in report coredump

application/displaycontent.cpp, application/logauththread.cpp, application/utils.h
Resolve the issue of incomplete display of crash logs
Log: Resolve the issue of incomplete display of crash logs
Bug: https://pms.uniontech.com/bug-view-234131.html
=> fix: Resolve the issue of incomplete display of crash logs

application/logbackend.cpp, logViewerService/logviewerservice.cpp, logViewerService/logviewerservice.h
Resolve the issue of adding sudo not being able to export logs
Log: Resolve the issue of adding sudo not being able to export logs
Bug: https://pms.uniontech.com/bug-view-238985.html
=> fix: Resolve the issue of adding sudo not being able to export logs

application/dbusmanager.cpp, application/dbusmanager.h, application/utils.cpp, logViewerService/logviewerservice.cpp
Resolve the issue of Sudo export logs being empty
Log: Resolve the issue of Sudo export logs being empty
Bug: https://pms.uniontech.com/bug-view-238985.html
=> fix: Resolve the issue of Sudo export logs being empty

application/logfileparser.cpp
Fix the issue of filter option filtering without content when there is only one submodule
Log: Fix the issue of filter option filtering without content when there is only one submodule
Bug: https://pms.uniontech.com/bug-view-244901.html
=> fix: Fix the issue of filter option filtering without content when there is only one submodule

application/configs/coredump-reporter.timer, application/logauththread.cpp, application/logauththread.h, application/structdef.h, application/utils.cpp, application/utils.h
1.When kwin/Xwayland crash, report the last 100 lines log.
2.To ensure the timeliness of kwin.log, the crash reporting task
has been adjusted to be triggered every 30 seconds
Log: kwin crash log buried point report
Task: https://pms.uniontech.com/task-view-330013.html
=> feat: kwin crash log buried point report

application/wtmpparse.cpp, application/wtmpparse.h
修复在32位操作系统上使用64位time_t构建失败
Bug: https://pms.uniontech.com/bug-view-250313.html
Log: 修复在32位操作系统上使用64位time_t构建失败
=> fix: 修复在32位操作系统上使用64位time_t构建失败

application/configs/dconfig/org.deepin.log.viewer.json, application/dbusproxy/dldbushandler.cpp, application/dbusproxy/dldbushandler.h, application/dbusproxy/dldbusinterface.h, application/displaycontent.cpp, application/gschema/com.deepin.log.viewer.gschema.xml, application/logapplicationhelper.cpp, application/logapplicationhelper.h, application/logauththread.cpp, application/logbackend.cpp, application/logbackend.h, application/structdef.h, application/utils.cpp, application/utils.h, logViewerService/assets/data/com.deepin.logviewer.xml, logViewerService/logviewerservice.cpp, logViewerService/logviewerservice.h
Crash report content optimization
1.add key of coredumpListCount: Record the number of query results for the ‘sudo coredumpctl list’ command;
2.add key of repeatCoredumps: Record the number of times crash information appears in different time ranges from the last reported time node to the current time node;
3.Definition of high-frequency crash application: The number of crashes accounts for more than 80% of the total number of newly added crashes, or occurs more than 3 times repeatedly;
4.Add the coredumpReportMax(default to 50) parameter configuration in Dconfig/Gsettings to limit the maximum number of entries per report;
6.About coredump detail infos, such as maps info, only report the first 200 rows;
7.Analyze the business code of crash details information and trigger it when adjusting …
=> feat: Crash report content optimization

application/displaycontent.cpp, application/displaycontent.h
Fix crashes when there is no permission to view other logs
Log: Fix crashes when there is no permission to view other logs
Bug: https://pms.uniontech.com/bug-view-266019.html
=> fix: Fix crashes when there is no permission to view other logs

application/logauththread.cpp, application/main.cpp, application/utils.cpp, application/utils.h
[feat: adapt treeland](https://github.com/linuxdeepin/deepin-log-viewer/commit/d39e6284c1616de637afaf0ad137dcceae3f83ee) 
Adapt Treeland, disable kwayland-shell in
Treeland enviroment.
Log: Adapt Treeland.
Influence: Treeland
[fix: out-of-bounds access error](https://github.com/linuxdeepin/deepin-log-viewer/commit/38280001c536c137f155766552f66696cbc67330) 
As title.
Log: Fix out-of-bounds access error
=> feat: adapt treeland and fix error

application/logdetailinfowidget.cpp
Resolve the issue of incorrect color display when switching themes on the log details page
Log: Resolve the issue of incorrect color display when switching themes on the log details page
Bug: https://pms.uniontech.com/bug-view-281647.html
=> fix: [theme] Resolve the issue of incorrect color display when switching themes on the log details page

application/main.cpp, application/utils.cpp, application/utils.h, debian/changelog
remove kwayland-shell env
Log: remove kwayland-shell env
=> fix: remove kwayland-shell env

logViewerService/logviewerservice.cpp, logViewerService/logviewerservice.h
Security reinforcement only authentication(TWB)
Log: Security reinforcement only authentication(TWB)
=> fix: Security reinforcement only authentication(TWB)

application/filtercontent.cpp
Remove the combobox automation tag and the community version cannot be used
Log: Remove the combox automation tag
=> fix: Remove the combox automation tag

.gitignore, application/dbusproxy/dldbushandler.cpp, logViewerService/assets/data/deepin-log-viewer-daemon.service
Secure the Logviewer service
Log: Secure the Logviewer service
Task: https://pms.uniontech.com/task-view-355359.html
=> feat: Secure the Logviewer service

logViewerService/CMakeLists.txt, logViewerService/logviewerservice.cpp, logViewerService/logviewerservice.h
The service did not read logs by gio, the gio-qt have include qt6 and qt5 libraries since v0.0.14, rollback codes.
Log: Fix can not get any logs issue.
=> fix: Fix can not get any logs issue

application/dbusproxy/dldbushandler.cpp
DBus interface returns QString type, but the frontend receives it as bool, causing continuous error logic.
Log: fix <can`t open audit log by deepin-log-viewer>
Bug: https://pms.uniontech.com/bug-view-302415.html
=> fix: isFileExist DBus interface return value handling logic

.tx/transifex.yaml, application/filtercontent.cpp, application/filtercontent.h, application/logauththread.cpp, application/logcollectormain.cpp, application/logcollectormain.h, application/loglistview.cpp, application/loglistview.h, application/logviewheaderview.cpp, application/logviewheaderview.h, application/logviewitemdelegate.cpp
Merge from 88bd74e92fb2381dbfe4aa0eb0f353eb546a58c8
to 2dd2fadd87582e528db2d9f51e78eb444bc82153
- we ignore treeland commits
=> chore: merge recent changes from master to release/eagle

.reuse/dep5, debian/control
- Remove unused build dependency from debian/control
Log: remove libdframeworkdbus-dev dependency
=> chore: remove libdframeworkdbus-dev dependency

.gitignore, application/utils.cpp, application/utils.h
- Deleted the isValidUserName and getHomePath functions from utils.cpp and utils.h as they were not utilized in the codebase.
- Updated .gitignore to include new AI-related files.
Log: Adapt to V23 dde dbus interface
=> refactor: Remove isValidUserName and getHomePath functions

application/assets/deepin-log-viewer/log-viewer/en_US/log-viewer.md, application/assets/deepin-log-viewer/log-viewer/zh_CN/log-viewer.md, application/assets/deepin-log-viewer/log-viewer/zh_HK/log-viewer.md, application/assets/deepin-log-viewer/log-viewer/zh_TW/log-viewer.md, debian/changelog
fix: Update log viewer titles for consistency
- Removed spaces around the pipe symbol in the titles of log-viewer markdown files for en_US, zh_CN, zh_HK, and zh_TW to ensure uniformity across different language versions.
bug: https://pms.uniontech.com/bug-view-321185.html
=>  fix: Update log viewer titles for consistency     

application/logbackend.cpp, application/logfileparser.cpp
- Combine duplicate filtering logic in logbackend.cpp into single more efficient implementation
- Add default filter case in logfileparser.cpp to handle logs without submodules
- Improve submodule filtering consistency across both files
log: as title
Bug: https://pms.uniontech.com/bug-view-309739.html
=> fix: log filtering and parsing logic

application/logallexportthread.cpp, application/logallexportthread.h, application/logbackend.cpp, application/logcollectormain.cpp, logViewerService/logviewerservice.cpp
Replace temporary file-based export with direct ZIP streaming using minizip library. This eliminates intermediate file creation and system command dependencies, significantly improving performance and reliability for large log exports.
Log:  Use direct zip streaming for export all logs.
Bug: https://pms.uniontech.com/bug-view-323639.html
=> fix: rework log export mechanism to use direct zip streaming
