linuxdeepin/deepin-log-viewer

- application/CMakeLists.txt
- application/eventlogutils.cpp
- application/eventlogutils.h
- application/main.cpp
Description: 提交埋点需求，采集日志搜集工具启动数据
Log: 提交埋点需求，采集日志搜集工具启动数据
> feat: 提交埋点需求，采集日志搜集工具启动数据

- debian/changelog
- debian/source/format
- logViewerService/logviewerservice.cpp
进一步完善反shell注入
Log: 进一步完善反shell注入
> fix: 进一步完善反shell注入

- debian/changelog
- debian/source/format
- logViewerService/logviewerservice.cpp
进一步完善反shell注入
Log: 进一步完善反shell注入
> fix: 进一步完善反shell注入 (#78)

- debian/changelog
- debian/source/format
- logViewerService/logviewerservice.cpp
同步反shell注入修改
Log: 同步反shell注入修改
> fix: 同步反shell注入修改

- tests/CMakeLists.txt
> fix: debian build

- debian/deepin-log-viewer.1
- debian/logViewerAuth.1
- debian/logViewerTruncate.1
Description: 开源合规debian目录.1文件整改
Log: 开源合规debian目录.1文件整改
> fix: 开源合规debian目录.1文件整改

- .tx/deepin.conf
- debian/changelog
Description: 修改changelog版本
Log: 修改changelog版本
> feat: 修改changelog版本

- debian/control
debian sid use libfftw3-dev and remove libfftw3-3
Log:
> chore: add libfftw3-dev in debian sid

- application/logapplicationhelper.cpp
- logViewerService/logviewerservice.cpp
Description: 非法调用算法问题，不应该用应用desktop路径与应用可执行程序路径对比
Log: 修复报错“is not allowed to configrate firewall”的问题
> fix: 修复报错“is not allowed to configrate firewall”的问题

- application/logapplicationhelper.cpp
Description: 去掉重复的配置项
Log: 修复其他日志中，日志配置重复
Bug: https://pms.uniontech.com/bug-view-182917.html
> fix: 修复其他日志中，日志配置重复

- debian/changelog
Description: 修改changelog版本
Log: 修改changelog版本
> fix: 修改changelog版本

- logViewerService/logviewerservice.cpp
Description: 增加读取隐藏文件
Log: 修复自定义日志配置，无法读取隐藏文件的内容
Bug: https://pms.uniontech.com/bug-view-183041.html
> fix: 修复自定义日志配置，无法读取隐藏文件的内容

- application/displaycontent.cpp
- application/displaycontent.h
- application/logdetailinfowidget.cpp
- application/logdetailinfowidget.h
- application/logoocfileparsethread.cpp
Description: 对告警文本做局中显示处理
Log: 修复其他日志中，无权限文案显示位置未居中
Bug: https://pms.uniontech.com/bug-view-182947.html
> fix: 修复其他日志中，无权限文案显示位置未居中

- application/CMakeLists.txt
- application/logapplicationhelper.cpp
- application/logapplicationhelper.h
Description: DConfig特性在1040镜像不支持，修改CMake工程配置，以便在Dtk版本支持Dconfig时使用组策略
Log: DConfig组策略功能在低版本解耦
> fix: DConfig组策略功能在低版本解耦

- application/CMakeLists.txt
- application/logapplicationhelper.cpp
- application/logapplicationhelper.h
Description: 解决DConfig组策略在低版本打包失败的问题
Log: 解决DConfig组策略在低版本打包失败的问题
> fix: 解决DConfig组策略在低版本打包失败的问题

- application/dbusmanager.cpp
- application/logapplicationhelper.cpp
- application/logapplicationhelper.h
- application/utils.cpp
- application/utils.h
- debian/control
1.兼容V23的dbus接口
2.移除对systeminfo接口的依赖
3.移除构建时对fftw的依赖
Log: 兼容V23，优化部分代码
> feat: 兼容V23，优化部分代码

- application/logapplicationhelper.cpp
未知原因导致CI没有检查出构建问题，已修复
Log: 修复构建失败
> fix: 修复构建失败

- application/logapplicationhelper.cpp
> chore: 生成topic

- application/logallexportthread.cpp
- application/logdetailinfowidget.cpp
- application/logdetailinfowidget.h
修复导出文件不全，修复UI对齐问题
Log: 修复导出文件不全，修复UI对齐问题
> fix: 修复导出文件不全，修复UI对齐问题

- debian/changelog
> chore: 修改changelog

- debian/changelog
> fix: 添加新tag

- debian/changelog
> chore: 修改版本号

- debian/changelog
update version to 6.0.7
Log: update version to 6.0.7
> chore: update version to 6.0.7

- application/configs/org.deepin.deepin-log-viewer.json
- application/dbusmanager.cpp
- application/dbusmanager.h
- application/logapplicationhelper.cpp
- application/loglistview.cpp
- application/utils.cpp
- application/utils.h
Description: hw机型判断适配dconfig
Log: hw机型判断适配dconfig
Task: https://pms.uniontech.com/task-view-276433.html
> feat: hw机型判断适配dconfig

- application/assets/com.deepin.pkexec.logViewerAuth.policy
- application/assets/com.deepin.pkexec.logViewerAuth.policy.tmp
- application/logallexportthread.cpp
- application/logauththread.cpp
- application/logcollectormain.cpp
- application/logdetailinfowidget.cpp
- debian/deepin-log-viewer.install
- translations/deepin-log-viewer_zh_CN.ts
- translations/deepin_log_viewer.ts
- translations/deepin_log_viewer_en_US.ts
- translations/policy/auth/policy.ts
- translations/policy/auth/policy_zh_CN.ts
> 审计日志-bug修复专题

- translations/deepin-log-viewer_zh_CN.ts
> fix: 翻译文案修改

- application/displaycontent.cpp
- application/displaycontent.h
- application/filtercontent.cpp
- application/logauththread.cpp
- application/logauththread.h
- application/logdetailinfowidget.cpp
- application/logdetailinfowidget.h
- application/logexportthread.cpp
- application/logexportthread.h
- application/logfileparser.cpp
- application/logfileparser.h
- application/loglistview.cpp
- application/structdef.h
- application/utils.cpp
- application/utils.h
- logViewerAuth/viewapplication.cpp
- logViewerService/logviewerservice.cpp
- translations/deepin-log-viewer.ts
添加崩溃日志收集功能
Log: 添加崩溃日志收集功能
Task: https://pms.uniontech.com/task-view-279017.html
> feat: 崩溃日志收集

- translations/deepin-log-viewer.ts
- translations/deepin-log-viewer_zh_CN.ts
> chore: 更新中文翻译

- application/DebugTimeManager.cpp
- application/dbusmanager.cpp
- application/logallexportthread.cpp
- application/logbackend.cpp
- application/main.cpp
- logViewerService/logviewerservice.cpp
1.全部导出-coredump文件导出
2.支持tty2、远端cmd命令导出
3.导出的txt文后缀改为log
4.修复 -e . 参数导出失败的问题
Log: 全部导出-支持coredump文件导出
> feat: 全部导出-支持coredump文件导出

- application/CMakeLists.txt
- application/cliapplicationhelper.cpp
- application/cliapplicationhelper.h
- application/main.cpp
CLI命令支持单实例运行
Log: CLI命令支持单实例运行
> fix: CLI命令支持单实例运行

- application/logapplicationhelper.cpp
其他日志添加窗管日志和配置文件显示
Log: 其他日志添加窗管日志和配置文件显示
> feat: 其他日志添加窗管日志和配置文件显示

- application/displaycontent.cpp
- application/displaycontent.h
- tests/src/ut_displaycontent.cpp
其他日志、自定义日志补齐搜索功能
Log: 其他日志、自定义日志补齐搜索功能
> fix: 其他日志、自定义日志补齐搜索功能

- application/CMakeLists.txt
fix 1042 build fail
Log: fix 1042 build fail
> fix: fix 1042 build fail

- application/logapplicationhelper.cpp
修复窗管日志不显示内容的问题
Log: 修复窗管日志不显示内容的问题
> fix: 修复窗管日志不显示内容的问题

- application/logallexportthread.cpp
全部导出other目录改为others
Log: 全部导出other目录改为others
> fix: 全部导出other目录改为others

- application/logapplicationhelper.cpp
- application/loglistview.cpp
修复kwin_x11日志显示无内容，全部导出无该文件的问题
Log: 修复kwin_x11日志显示无内容，全部导出无该文件的问题
> fix: 修复kwin_x11日志显示无内容，全部导出无该文件的问题

- application/logapplicationhelper.cpp
- application/logexportthread.cpp
> fix: 窗管默认日志路径应加.

- application/CMakeLists.txt
- application/accessible.h
- application/displaycontent.cpp
- application/displaycontent.h
- application/filtercontent.cpp
- application/logcollectormain.cpp
- application/loglistview.cpp
- application/main.cpp
添加accessible标签名称
Log: 添加accessible标签名称
> feat: 添加accessible标签名称

- application/displaycontent.cpp
Fix the issue of successfully exporting read-only file directories
Log: Fix the issue of successfully exporting read-only file directories
Bug: https://pms.uniontech.com/bug-view-217957.html
> fix: Fix the issue of successfully exporting read-only file directories

- application/main.cpp
Command line export add authentication window
Log: Command line export add authentication window
Bug: https://pms.uniontech.com/bug-view-218757.html
> fix: Command line export add authentication window

- application/assets/deepin-logger
- application/main.cpp
Add pkexec to implement command line export authentication
Log: Add pkexec to implement command line export authentication
Bug: https://pms.uniontech.com/bug-view-218757.html
> fix: Add pkexec to implement command line export authentication

- application/logallexportthread.cpp
Fix UI - issue of all export failures
Log: Fix UI - issue of all export failures
> fix: Fix UI - issue of all export failures

- 3rdparty/DocxFactory/src/locale/LocaleFunc.cpp
- application/CMakeLists.txt
- application/assets/deepin-log-viewer.json
- application/dbusproxy/dldbushandler.cpp
- application/displaycontent.cpp
- application/displaycontent.h
- application/filtercontent.cpp
- application/journalbootwork.cpp
- application/journalwork.cpp
- application/logallexportthread.cpp
- application/logapplicationparsethread.cpp
- application/logauththread.cpp
- application/logcombox.cpp
- application/logexportthread.cpp
- application/logfileparser.cpp
- application/loglistview.cpp
- application/logoocfileparsethread.cpp
- application/main.cpp
- application/sharedmemorymanager.cpp
- application/utils.cpp
- application/wtmpparse.cpp
- debian/deepin-log-viewer.install
- liblogviewerplugin/src/plugins/logviewerplugin.cpp
- logViewerAuth/viewapplication.cpp
- logViewerService/logviewerservice.cpp
- logViewerService/main.cpp
- logViewerTruncate/main.cpp
Adaptation log specification rectification
Log: Adaptation log specification rectification
Task: https://pms.uniontech.com/task-view-292081.html
> feat: Adaptation log specification rectification

- application/logallexportthread.cpp
- application/logfileparser.cpp
fix app list can not show/export logs
Log: fix app list can not show/export logs
> fix: fix app list can not show/export logs

- application/logallexportthread.cpp
- application/logapplicationhelper.cpp
- application/logfileparser.cpp
- application/main.cpp
- logViewerService/main.cpp
Rectification of log specification adaptation compatibility
Log: Rectification of log specification adaptation compatibility
Task: https://pms.uniontech.com/task-view-296703.html
> feat: Rectification of log specification adaptation compatibility

- application/logapplicationhelper.cpp
- application/utils.cpp
fix journal app can not show problems
Log: fix journal app can not show problems
> fix: fix journal app can not show problems

- application/DebugTimeManager.cpp
- application/cliapplicationhelper.cpp
- application/dbusmanager.cpp
- application/dbusproxy/dldbushandler.cpp
- application/displaycontent.cpp
- application/journalappwork.cpp
- application/journalbootwork.cpp
- application/journalwork.cpp
- application/logallexportthread.cpp
- application/logapplicationhelper.cpp
- application/logapplicationparsethread.cpp
- application/logbackend.cpp
- application/logexportthread.cpp
- application/logfileparser.cpp
- application/logoocfileparsethread.cpp
- application/main.cpp
- application/sharedmemorymanager.cpp
- application/utils.cpp
- logViewerAuth/viewapplication.cpp
- logViewerService/logviewerservice.cpp
Change app log category name
Log: Change app log category name
> chore: Change app log category name

- debian/changelog
相关PR:
* #183
* #184
* #186
* #187
* #188
* #189
* #190
Log: Update version to 6.1.2
> chore: Update version to 6.1.2

- application/structdef.h
Update REUSE date
Log: Update REURE date
> chore: Update REUSE date

- debian/changelog
相关PR:
* #191
* #193
* #194
* #195
* #196
* #197
* #198
* #200
Log: Update version to 6.1.3
> chore: Update version to 6.1.3

- application/logapplicationhelper.cpp
Fix the issue of low version iso app log  not being displayed
Log: Fix the issue of low version iso app log  not being displayed
> fix: Fix the issue of low version iso app log  not being displayed

- debian/changelog
相关PR:
* #202
Log: Update version to 6.1.4
> chore: Update version to 6.1.4

- application/logapplicationhelper.cpp
- application/logbackend.cpp
- application/logbackend.h
- application/main.cpp
- application/structdef.h
- application/utils.cpp
- translations/deepin-log-viewer.ts
Rich command line export function
Log: Rich command line export function
> feat: Rich command line export function

- application/assets/deepin-logger
- application/main.cpp
- translations/deepin-log-viewer.ts
Remove command authentication
Log: Remove command authentication
> fix: Remove command authentication

- application/logbackend.cpp
- application/logbackend.h
- application/main.cpp
CLI export type logs to diretory
Log: CLI export type logs to diretory
Bug: https://pms.uniontech.com/bug-view-225107.html
> fix: CLI export type logs to diretory

- application/dbusmanager.cpp
- application/logbackend.cpp
- application/main.cpp
CLI export return correct errcode
Log: CLI export return correct errcode
Bug: https://pms.uniontech.com/bug-view-225365.html
> fix: CLI export return correct errcode

- application/logbackend.cpp
- application/logbackend.h
- application/main.cpp
fix cli export to no-write dir can not quit
Log: fix cli export to no-write dir can not quit
Bug: https://pms.uniontech.com/bug-view-225553.html
> fix: fix cli export to no-write dir can not quit

- application/logbackend.cpp
- application/main.cpp
fix cli export app by keyword failed
Log: fix cli export app by keyword failed
Bug: https://pms.uniontech.com/bug-view-225573.html
> fix: fix cli export app by keyword failed

- application/main.cpp
fix cli export '-e' parameter is required option
Log: fix cli export '-e' parameter is required option
> fix: fix cli export '-e' parameter is required option

- application/logbackend.cpp
fix cli export audit log other bug contain MAC audit type log
Log: fix cli export audit log other bug contain MAC audit type log
Bug: https://pms.uniontech.com/bug-view-225793.html
> fix: fix cli export audit log other bug contain MAC audit type log

- application/displaycontent.cpp
- application/logbackend.cpp
CLI export type log folder name with timestamp
Log: CLI export type log folder name with timestamp
> feat: CLI export type log folder name with timestamp

- application/logbackend.cpp
- application/main.cpp
Improve the validity verification and judgment logic of cli export conditions
Log: Improve the validity verification and judgment logic of cli export conditions
> fix: Improve the validity verification and judgment logic of cli export conditions

- application/logallexportthread.cpp
- application/logbackend.cpp
- logViewerService/logviewerservice.cpp
CLI export app log only export app log file
Log: CLI export app log only export app log file
Bug: https://pms.uniontech.com/bug-view-226589.html
> fix: CLI export app log only export app log file

- application/journalappwork.cpp
fix journal app log can't show by period
Log: fix journal app log can't show by period
Bug: https://pms.uniontech.com/bug-view-226727.html
> fix: fix journal app log can't show by period

- application/CMakeLists.txt
- application/configs/coredump-reporter.service
- application/configs/coredump-reporter.timer
- application/eventlogutils.cpp
- application/eventlogutils.h
- application/logbackend.cpp
- application/logbackend.h
- application/logfileparser.cpp
- application/logsettings.cpp
- application/logsettings.h
- application/main.cpp
- application/structdef.h
- debian/deepin-log-viewer.install
- translations/deepin-log-viewer.ts
add report coredump feature
Log: add report coredump feature
Task: https://pms.uniontech.com/story-view-31473.html
> feat: add report coredump feature

- application/logbackend.cpp
Fix the issue of no data in today's audit log exported by cli
Log: Fix the issue of no data in today's audit log exported by cli
Bug: https://pms.uniontech.com/bug-view-227109.html
> fix: Fix the issue of no data in today's audit log exported by cli

- debian/changelog
Update version to 6.1.5
相关PR:
* #228
* #225
* #206
* #205
Log: Update version to 6.1.5
> chore: Update version to 6.1.5

- application/displaycontent.cpp
- application/logcollectormain.cpp
- application/logdetailinfowidget.cpp
- application/logspinnerwidget.cpp
clear qt warning logs
Log: clear qt warning logs
> fix: clear qt warning logs

- application/logallexportthread.cpp
- application/logbackend.cpp
Fix the issue of incomplete acquisition of file base names
Log: Fix the issue of incomplete acquisition of file base names
Bug: https://pms.uniontech.com/bug-view-228425.html
> fix: Fix the issue of incomplete acquisition of file base names

- application/logauththread.cpp
- application/structdef.h
report coredump add stackinfo
Log: report coredump add stackinfo
https://pms.uniontech.com/story-view-31473.html
> feat: report coredump add stackinfo

- application/logauththread.cpp
- application/structdef.h
- logViewerAuth/viewapplication.cpp
> fix: not get core file maps

- application/logauththread.cpp
- logViewerAuth/viewapplication.cpp
- logViewerService/logviewerservice.cpp
Resolve the issue of failure to obtain stack maps address for crash information
Log: Resolve the issue of failure to obtain stack maps address for crash information
> fix: Resolve the issue of failure to obtain stack maps address for crash information

- debian/changelog
Update Version to 6.1.6
相关PR:
* #233
* #234
* #235
* #237
* #238
Log: Update version to 6.1.6
> chore: Update version to 6.1.6

- application/main.cpp
Fix security vulnerabilities introduced by LD_PRELOAD
Log: Fix security vulnerabilities introduced by LD_PRELOAD
Bug: HW23-1232
> fix: Fix security vulnerabilities introduced by LD_PRELOAD

- application/configs/coredump-reporter.service
- debian/deepin-log-viewer.install
- logViewerService/CMakeLists.txt
- logViewerService/assets/data/com.deepin.logviewer.service
- logViewerService/assets/data/deepin-log-viewer-daemon.service
Rectification of DBus security coding standards
Log: Rectification of DBus security coding standards
> feat: Rectification of DBus security coding standards

- application/configs/coredump-reporter.service
- logViewerService/assets/data/deepin-log-viewer-daemon.service
systemd service add memory limits 8G
Log: systemd service add memory limits 8G
> fix: systemd service add memory limits 8G

- application/configs/coredump-reporter.service
- application/logauththread.cpp
- logViewerService/assets/data/deepin-log-viewer-daemon.service
Code review issue modification
Log: Code review issue modification
> chore: Code review issue modification

- debian/changelog
Update version to 6.1.7
相关PR:
* #240
* #241
* #242
* #243
* #244
* #245
Log: Update version to 6.1.7
> chore: Update version to 6.1.7

- application/logbackend.cpp
- application/logcollectormain.cpp
- application/main.cpp
- logViewerService/logviewerservice.cpp
Optimization of output path whitelist inspection methods
Log: Optimization of output path whitelist inspection methods
Bug: https://pms.uniontech.com/bug-view-236471.html
> chore: Optimization of output path whitelist inspection methods

- debian/changelog
Update version to 6.1.8
相关PR:
* #247
* #248
Log: Update version to 6.1.8
> chore: Update version to 6.1.8

- application/assets/deepin-log-viewer.json
- application/displaycontent.cpp
- application/displaycontent.h
- application/logallexportthread.cpp
- application/logauththread.cpp
- application/logbackend.cpp
- application/logbackend.h
- application/logexportthread.cpp
- application/logfileparser.cpp
- application/logfileparser.h
- application/main.cpp
- application/sharedmemorymanager.cpp
- application/sharedmemorymanager.h
- application/structdef.h
- application/utils.cpp
- logViewerService/logviewerservice.cpp
- logViewerService/main.cpp
- tests/CMakeLists.txt
- tests/src/ut_displaycontent.cpp
1.merge interface display and data acquisition process for cli export
2.add submodule parameter for cli export
3.merge single app export code to LogBackend
4.export all - improved app export feature
5.compatibility guarantee
Log: Log specification adaptation 2nd
> feat: Log specification adaptation 2nd- merge export

- application/filtercontent.cpp
Resolve the issue of JSON configuration not being able to control application visibility
Log: Resolve the issue of JSON configuration not being able to control application visibility
Bug: https://pms.uniontech.com/bug-view-237801.html
> fix: Resolve the issue of JSON configuration not being able to control application visibility

- application/filtercontent.cpp
Resolve the issue of blank items in the application list
Log: Resolve the issue of blank items in the application list
Bug: https://pms.uniontech.com/bug-view-237785.html
> fix: Resolve the issue of blank items in the application list

- application/logauththread.cpp
- application/structdef.h
add package version information on crash burial point
Log: add package version information on crash burial point
Bug: https://pms.uniontech.com/bug-view-236991.html
> feat: add package version information on crash burial point

- application/configs/dconfig/org.deepin.log.viewer.json
- application/configs/debugconfig/org.deepin.log.viewer.json
- application/utils.cpp
1.Change the JSON visible field to 0 in debugging mode configuration
2.change dconfig log_ruleus default value
Log: Change the JSON visible field to 0 in debugging mode configuration
Bug: https://pms.uniontech.com/bug-view-238925.html
> fix: Change the JSON visible field to 0 in debugging mode configuration

- debian/changelog
Update version 6.1.10
Log: Update version 6.1.10
> chore: Update version 6.1.10

- application/configs/debugconfig/org.deepin.log.viewer.json
modify debug-config json
Log: modify debug-config json
Bug: https://pms.uniontech.com/bug-view-239503.html
> fix: modify debug-config json

- application/structdef.h
- debian/changelog
Update version to 6.1.11
相关PR:
* #261
Log: Update version to 6.1.11
> chore: Update version to 6.1.11

- application/main.cpp
- logViewerService/logviewerservice.cpp
1.add -v opntion version info
2.improve the process of reading application log paths
Log: Add -v option version info
Bug: https://pms.uniontech.com/bug-view-236241.html
> fix: Add -v option version info

- application/dbusmanager.cpp
- application/dbusmanager.h
- application/logauththread.cpp
- application/logbackend.cpp
- application/logcollectormain.cpp
- application/loglistview.cpp
- tests/src/ut_dbusmanager.cpp
- tests/src/ut_loglistview.cpp
Adapt to the type of PGX log display
Log: Adapt to the type of PGX log display
Bug: https://pms.uniontech.com/bug-view-240851.html
> fix: Adapt to the type of PGX log display

- debian/changelog
Update version to 6.1.12
相关PR:
* #264
* #263
Log: Update version to 6.1.12
> chore: Update version to 6.1.12

- application/logbackend.cpp
- application/logbackend.h
- application/utils.cpp
Fix the issue of parent directory permissions being changed during export
Log: Fix the issue of parent directory permissions being changed during export
> fix: Fix the issue of parent directory permissions being changed during export

- logViewerService/logviewerservice.cpp
Unzip may overwrite linked file data.
1. Check valid invoker.
2. Clean previous unzip file.
3. Creates temporary file on each call, avoid
link previous temporary files.
Log: Decompression may overwrite linked file data
Bug: https://pms.uniontech.com/bug-view-243387.html
> fix: Unzip may overwrite linked file data

- application/logapplicationhelper.cpp
fix app name can not show chinese
Log: fix app name can not show chinese
> fix: fix app name can not show chinese

- debian/changelog
Update version to 6.1.13
相关PR:
* #266
* #267
* #268
* #269
* #270
* #271
Log: Update version to 6.1.13
> chore: Update version to 6.1.13

- application/logauththread.cpp
- logViewerService/logviewerservice.cpp
- logViewerService/logviewerservice.h
Delete dump temporary file from service backend
Log: Delete dump temporary file from service backend
Bug: https://pms.uniontech.com/bug-view-241927.html
> fix: Delete dump temporary file from service backend

- application/configs/coredump-reporter.timer
- application/logauththread.cpp
- logViewerService/logviewerservice.cpp
Crash reporting adjusted to once every 30 seconds
Log: Crash reporting adjusted to once every 30 seconds
> chore: Crash reporting adjusted to once every 30 seconds

- application/logauththread.cpp
- logViewerService/logviewerservice.cpp
This reverts commit 2f014560959c463b5474dd605d63de79285df4a0.
> Revert "chore: add logs"

- debian/changelog
Update version to 6.1.14
相关PR:
* #273
* #274
* #275
Log: Update version to 6.1.14
> chore: Update version to 6.1.14

- application/configs/coredump-reporter.timer
1.adjust coredump report interval to 10m
Log: adjust coredump report interval
> chore: adjust coredump report interval

- application/logbackend.cpp
Correction of abnormal last reporting time
Log: Correction of abnormal last reporting time
> fix: Correction of abnormal last reporting time

- debian/changelog
Update version to 6.1.15
Log: Update version to 6.1.15
> chore: Update version to 6.1.15

- application/CMakeLists.txt
- application/configs/coredump-reporter.service
- debian/deepin-log-viewer.install
- debian/deepin-log-viewer.postinst
The coredump reporter service switches from system mode to user mode
Log: The coredump reporter service switches from system mode to user mode
> fix: The coredump reporter service switches from system mode to user mode

- debian/changelog
Update version to 6.1.16
Log: Update version to 6.1.16
> tag:6.1.16

- application/displaycontent.cpp
- application/displaycontent.h
- application/logbackend.cpp
- application/logbackend.h
- application/logfileparser.h
- application/parsethread/parsethreadbase.cpp
- application/parsethread/parsethreadbase.h
- application/parsethread/parsethreadkern.cpp
- logViewerService/logviewerservice.cpp
Memory optimization bug fix
Log: Memory optimization bug fix
Bug: https://pms.uniontech.com/bug-view-251515.html
> perf: Memory optimization bug fix

- application/logbackend.cpp
Refinement of kernel log segmentation export and cancellation of authentication logic
Log: Refinement of kernel log segmentation export and cancellation of authentication logic
> fix: Refinement of kernel log segmentation export and cancellation of authentication logic

- application/displaycontent.cpp
- application/displaycontent.h
- application/logbackend.cpp
- application/logbackend.h
- application/sharedmemorymanager.cpp
Search function optimization 2nd && add logs
Log: Search function optimization 2nd && add logs
> fix: Search function optimization 2nd && add logs

- debian/changelog
相关PR如下:
* #287 
* #288 
* #289 
* #290 
Log: Update version to 6.1.17
> chore: Update version to 6.1.17

- application/CMakeLists.txt
- application/displaycontent.cpp
- application/logbackend.cpp
- application/logbackend.h
- application/logsegementexportthread.cpp
- application/logsegementexportthread.h
- application/logtreeview.h
- tests/CMakeLists.txt
Segement export to doc/xls/txt/html and bug fix
Log: Segement export to doc/xls/txt/html and bug fix
Bug: https://pms.uniontech.com/bug-view-251937.html
> feat: Segement export to doc/xls/txt/html and bug fix

- logViewerService/logviewerservice.cpp
fix 2 security vulnerabilities about LD_PRELOAD
Log: Fix two security vulnerabilities
Bug: https://pms.uniontech.com/bug-view-253967.html
> fix: Fix two security vulnerabilities

- application/displaycontent.cpp
- logViewerService/logviewerservice.cpp
- logViewerService/logviewerservice.h
Save the line offset
Log: Fixed some known issues
> fix: Optimized file reading speed

- application/displaycontent.cpp
1.Fix the issue of continuing the search after the search results are full page
2.Fix the issue where scrolling to the bottom cannot trigger segmented search
Log: Fix issues with abnormal search functionality
> fix: Fix issues with abnormal search functionality

- application/logapplicationhelper.cpp
fix compile problem on longarrch
Log: fix compile problem on longarrch
> fix: fix compile problem on longarrch

- logViewerService/logviewerservice.cpp
Security vulnerability reinforcement
Log: Security vulnerability reinforcement
> fix: Security vulnerability reinforcement

- logViewerService/logviewerservice.cpp
remove /bin/bash in service if necessary
Log: remove /bin/bash in service if necessary
> fix: remove /bin/bash in service if necessary

- application/filtercontent.cpp
The UI of application logs in the log collection tool overlaps when submodules exist.
Log: Change UI interface
Bug: https://pms.uniontech.com/bug-view-256789.html
> fix: UI interface in English

- application/filtercontent.cpp
页面内“级别”显示为“level
Log: 页面内“级别”显示为“level
Bug: https://pms.uniontech.com/bug-view-260291.html
> fix: 页面内“级别”显示为“level

- debian/changelog
相关PR:
* #293
* #294
* #299
* #300
* #301
* #302
* #303
* #304
* #305
* #306
Log: Update version to 6.1.18
> chore: Update version to 6.1.18

- application/logauththread.cpp
Code format organization
Log: Code format organization
> chore: Code format organization

- .gitignore
- application/dbusproxy/dldbushandler.cpp
- logViewerService/assets/data/deepin-log-viewer-daemon.service
Secure the Logviewer service
Log: Secure the Logviewer service
Task: https://pms.uniontech.com/task-view-355359.html
> feat: Secure the Logviewer service

- debian/deepin-log-viewer.postinst
Fix the issue of upgrade failure after enabling level protection
Log: Fix the issue of upgrade failure after enabling level protection
Bug: https://pms.uniontech.com/bug-view-258569.html
> fix: Fix the issue of upgrade failure after enabling level protection

- logViewerService/logviewerservice.cpp
DBus calls authentication adds MNT check
Log: DBus calls authentication adds MNT check
> fix: DBus calls authentication adds MNT check

- application/displaycontent.cpp
- application/displaycontent.h
- application/logallexportthread.cpp
- application/logauththread.cpp
- application/logbackend.cpp
- application/logexportthread.cpp
- application/loglistview.cpp
- application/loglistview.h
- application/utils.cpp
- application/utils.h
- logViewerAuth/viewapplication.cpp
- logViewerService/CMakeLists.txt
- logViewerService/logviewerservice.cpp
- logViewerService/logviewerservice.h
- logViewerService/logviewerwatcher.cpp
- logViewerService/logviewerwatcher.h
- logViewerTruncate/main.cpp
- translations/deepin-log-viewer.ts
- translations/deepin-log-viewer_zh_CN.ts
- translations/deepin_log_viewer.ts
Remove bash command invoke and DBus security reinforcement
Log: Remove bash command invoke and DBus security reinforcement
Task: https://pms.uniontech.com/task-view-362319.html
> fix: [cmd] Remove bash command invoke and DBus security reinforcement

- application/dbusproxy/dldbushandler.cpp
- application/dbusproxy/dldbusinterface.h
- logViewerService/assets/data/com.deepin.logviewer.xml
- logViewerService/logviewerservice.cpp
- logViewerService/logviewerservice.h
fix 3 security vulnerabilities
Log: fix 3 security vulnerabilities
Bug: https://pms.uniontech.com/bug-view-278915.html
> fix: fix 3 security vulnerabilities

- application/utils.cpp
fix compile problem
Log: fix compile problem
Bug: https://pms.uniontech.com/bug-view-278915.html
> fix: fix compile problem

- application/utils.cpp
- logViewerService/logviewerservice.cpp
- logViewerService/logviewerservice.h
for dbus scan
Log:  strong the dbus interface
Task: https://pms.uniontech.com/task-view-365257.html
> chore: [security] strong the dbus interface

- application/dbusproxy/dldbushandler.cpp
- application/dbusproxy/dldbushandler.h
- application/dbusproxy/dldbusinterface.h
- logViewerService/assets/data/com.deepin.logviewer.xml
- logViewerService/logviewerservice.cpp
- logViewerService/logviewerservice.h
fix boot log no content problem
Log: fix boot log no content problem
Bug: https://pms.uniontech.com/bug-view-278915.html
> fix: fix boot log no content problem

- application/assets/com.deepin.pkexec.logViewerAuth.policy.tmp
Fixed the issue of repeatedly popping up authentication windows when exporting logs
Log: Fixed the issue of repeatedly popping up authentication windows when exporting logs
Bug: https://pms.uniontech.com/bug-view-278819.html
> fix: Fixed the issue of repeatedly popping up authentication windows when exporting logs

- application/dbusproxy/dldbushandler.cpp
- application/dbusproxy/dldbusinterface.h
- application/logapplicationparsethread.cpp
- application/logauththread.cpp
- application/logoocfileparsethread.cpp
- logViewerService/assets/data/com.deepin.logviewer.xml
- logViewerService/logviewerservice.cpp
- logViewerService/logviewerservice.h
Fixed the issue of multiple authentication windows popping up for certain types
Log: Fixed the issue of multiple authentication windows popping up for certain types
Bug: https://pms.uniontech.com/bug-view-281209.html,https://pms.uniontech.com/bug-view-281199.html
> fix: Fixed the issue of multiple authentication windows popping up for certain types

- translations/deepin-log-viewer_zh_CN.ts
Xorg log offset international translation copywriting adjustment
Log: Xorg log offset international translation copywriting adjustment
> fix: [ts] Xorg log offset international translation copywriting adjustment

- application/filtercontent.cpp
- application/filtercontent.h
- application/logcollectormain.cpp
- application/logcollectormain.h
- application/loglistview.cpp
- application/loglistview.h
- application/logviewheaderview.cpp
- application/logviewheaderview.h
- application/logviewitemdelegate.cpp
adapt compact mode
Log: adpat compact mode
Bug: https://pms.uniontech.com/bug-view-279779.html
> fix: adapt compact mode

- application/filtercontent.cpp
- application/filtercontent.h
- application/logviewitemdelegate.cpp
- debian/changelog
update version to 6.5.2
Log: update version to 6.5.2
> chore: update version to 6.5.2

- debian/changelog
Bump version to 6.5.3
Log: Bump version to 6.5.3
> chore: Bump version to 6.5.3

- application/logdetailedit.cpp
remove invalid  url
Log: remove invalid  url
> fix: remove invalid  url

- .gitignore
- application/CMakeLists.txt
- application/assets/deepin-log-viewer.desktop
- application/assets/deepin-log-viewer.desktop.tmp
- application/main.cpp
- debian/control
- debian/deepin-log-viewer.install
- logViewerService/assets/data/com.deepin.logviewer.conf
- logViewerService/assets/data/com.deepin.logviewer.xml
- logViewerService/logviewerservice.cpp
- logViewerService/logviewerservice.h
- Added support for file descriptor arguments in main application for improved inter-process communication.
- Updated installation path for the log viewer executable to a more appropriate directory.
- Introduced a new method `SetAllowCaller` in the log viewer service to manage allowed callers, enhancing security checks.
Log: These changes reinforce security measures and improve the application's installation structure.
Task: https://pms.uniontech.com/task-view-370233.html
> ref: Enhance log viewer security and installation paths

- .gitignore
- application/CMakeLists.txt
- application/assets/deepin-log-viewer.desktop
- application/assets/deepin-log-viewer.desktop.tmp
- application/main.cpp
- debian/control
- debian/deepin-log-viewer.install
- logViewerService/assets/data/com.deepin.logviewer.conf
- logViewerService/assets/data/com.deepin.logviewer.xml
- logViewerService/logviewerservice.cpp
- logViewerService/logviewerservice.h
This reverts commit 4bb64fdb3583dcb4b3bad025a7317427bfeda77f.
> Revert "feat: Enhance DBus security and installation paths"

- debian/changelog
v6.5.7 release.
Log: v6.5.7 release.
> chore: [tag]New tag v6.5.7

- application/displaycontent.cpp
- application/exportprogressdlg.cpp
- application/filtercontent.cpp
- application/loglistview.cpp
- application/logviewheaderview.cpp
- application/main.cpp
The QButtonGroup's signal buttonClicked change to idClicked, that cause the log items do not response click.
Log: Fix log items did not response click.
> fix: Fix log items did not response click

- debian/changelog
Bump version to 6.5.9
Log: Bump version to 6.5.9
> chore: Bump version to 6.5.9

- application/logapplicationhelper.cpp
- Modified the createDesktopFiles function to search for desktop files in both "/usr/share/applications" and "/var/lib/linglong/entries/share/applications". Enhanced the logic to ensure proper filtering of applications based on specific criteria.
bug: https://pms.uniontech.com/bug-view-304279.html
> fix: Update desktop file search logic to include multiple directories

- application/journalbootwork.cpp
- application/journalwork.cpp
Fixed an exit crash
Log: Fixed an exit crash
bug: https://pms.uniontech.com/bug-view-316875.html
> fix: Fixed an exit crash

- application/journalbootwork.cpp
- application/journalwork.cpp
- application/logfileparser.cpp
- application/main.cpp
Fixed a crash issue with closing
Log: Fixed a crash issue with closing
bug: https://pms.uniontech.com/bug-view-316875.html
> fix: Fixed a crash issue with closing

- application/dbusproxy/dldbushandler.cpp
- application/dbusproxy/dldbushandler.h
- application/logallexportthread.cpp
- application/utils.cpp
- opsLogViewerService/logexportinterface.cpp
- opsLogViewerService/opslogexport.cpp
- opsLogViewerService/opslogexport.h
-- Change the get VAG log way.
Log: fix issue
Bug: https://pms.uniontech.com/bug-view-335611.html
> Fix: [ops-log] The VGA log show error.

- opsLogViewerService/CMakeLists.txt
-- Change ${CAMKE_INSTALL_BINDIR} to bin.
> Fix: [build-package] Build package failed on sw_64 and mips.

- application/dbusproxy/dldbushandler.cpp
-- some platform not export system_info.txt
Log: fix issue
Bug: https://pms.uniontech.com/bug-view-335879.html
> Fix: [ops-log] Log file missing.
